version: '3.8'

services:
  app:
    build: .
    container_name: my_nestjs_app
    ports:
      - "3000:3000"
    environment:
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DATABASE=${POSTGRES_DB}
    depends_on:
      - db
    networks:
      - app_network
      - postgres_network

  db:
    image: postgres:13
    container_name: postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - postgres_network

networks:
  app_network:
  postgres_network:




